controller_list:
  - name: left_arm_controller
    action_ns: ''
    type: FollowJointTrajectory
    default: true
    joints:
      - lower_arm_joint
      - upper_arm_joint
      - wrist_joint
  - name: left_scoop_controller
    action_ns: ''
    type: FollowJointTrajectory
    default: true
    joints:
      - scoop_joint
