controller_list:
  - name: fake_left_arm_controller
    joints:
      - upper_arm_joint
      - lower_arm_joint
      - wrist_joint
  - name: fake_left_scoop_controller
    joints:
      - scoop_joint