// Generated by gencpp from file ingredientfinder/ingredientPosResponse.msg
// DO NOT EDIT!


#ifndef INGREDIENTFINDER_MESSAGE_INGREDIENTPOSRESPONSE_H
#define INGREDIENTFINDER_MESSAGE_INGREDIENTPOSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ingredientfinder
{
template <class ContainerAllocator>
struct ingredientPosResponse_
{
  typedef ingredientPosResponse_<ContainerAllocator> Type;

  ingredientPosResponse_()
    : platformtarget(0.0)  {
    }
  ingredientPosResponse_(const ContainerAllocator& _alloc)
    : platformtarget(0.0)  {
    }



   typedef double _platformtarget_type;
  _platformtarget_type platformtarget;




  typedef boost::shared_ptr< ::ingredientfinder::ingredientPosResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ingredientfinder::ingredientPosResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ingredientPosResponse_

typedef ::ingredientfinder::ingredientPosResponse_<std::allocator<void> > ingredientPosResponse;

typedef boost::shared_ptr< ::ingredientfinder::ingredientPosResponse > ingredientPosResponsePtr;
typedef boost::shared_ptr< ::ingredientfinder::ingredientPosResponse const> ingredientPosResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ingredientfinder::ingredientPosResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ingredientfinder::ingredientPosResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ingredientfinder

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ingredientfinder::ingredientPosResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ingredientfinder::ingredientPosResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ingredientfinder::ingredientPosResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ingredientfinder::ingredientPosResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ingredientfinder::ingredientPosResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ingredientfinder::ingredientPosResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ingredientfinder::ingredientPosResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "506af8e66365d020696c006b9d2c8a41";
  }

  static const char* value(const ::ingredientfinder::ingredientPosResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x506af8e66365d020ULL;
  static const uint64_t static_value2 = 0x696c006b9d2c8a41ULL;
};

template<class ContainerAllocator>
struct DataType< ::ingredientfinder::ingredientPosResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ingredientfinder/ingredientPosResponse";
  }

  static const char* value(const ::ingredientfinder::ingredientPosResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ingredientfinder::ingredientPosResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 platformtarget\n\
\n\
";
  }

  static const char* value(const ::ingredientfinder::ingredientPosResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ingredientfinder::ingredientPosResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.platformtarget);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ingredientPosResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ingredientfinder::ingredientPosResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ingredientfinder::ingredientPosResponse_<ContainerAllocator>& v)
  {
    s << indent << "platformtarget: ";
    Printer<double>::stream(s, indent + "  ", v.platformtarget);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INGREDIENTFINDER_MESSAGE_INGREDIENTPOSRESPONSE_H
