// Generated by gencpp from file ingredientfinder/ingredientPos.msg
// DO NOT EDIT!


#ifndef INGREDIENTFINDER_MESSAGE_INGREDIENTPOS_H
#define INGREDIENTFINDER_MESSAGE_INGREDIENTPOS_H

#include <ros/service_traits.h>


#include <ingredientfinder/ingredientPosRequest.h>
#include <ingredientfinder/ingredientPosResponse.h>


namespace ingredientfinder
{

struct ingredientPos
{

typedef ingredientPosRequest Request;
typedef ingredientPosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ingredientPos
} // namespace ingredientfinder


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ingredientfinder::ingredientPos > {
  static const char* value()
  {
    return "5d2f1a75acc8986b11d8ddad2290d245";
  }

  static const char* value(const ::ingredientfinder::ingredientPos&) { return value(); }
};

template<>
struct DataType< ::ingredientfinder::ingredientPos > {
  static const char* value()
  {
    return "ingredientfinder/ingredientPos";
  }

  static const char* value(const ::ingredientfinder::ingredientPos&) { return value(); }
};


// service_traits::MD5Sum< ::ingredientfinder::ingredientPosRequest> should match 
// service_traits::MD5Sum< ::ingredientfinder::ingredientPos > 
template<>
struct MD5Sum< ::ingredientfinder::ingredientPosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ingredientfinder::ingredientPos >::value();
  }
  static const char* value(const ::ingredientfinder::ingredientPosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ingredientfinder::ingredientPosRequest> should match 
// service_traits::DataType< ::ingredientfinder::ingredientPos > 
template<>
struct DataType< ::ingredientfinder::ingredientPosRequest>
{
  static const char* value()
  {
    return DataType< ::ingredientfinder::ingredientPos >::value();
  }
  static const char* value(const ::ingredientfinder::ingredientPosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ingredientfinder::ingredientPosResponse> should match 
// service_traits::MD5Sum< ::ingredientfinder::ingredientPos > 
template<>
struct MD5Sum< ::ingredientfinder::ingredientPosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ingredientfinder::ingredientPos >::value();
  }
  static const char* value(const ::ingredientfinder::ingredientPosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ingredientfinder::ingredientPosResponse> should match 
// service_traits::DataType< ::ingredientfinder::ingredientPos > 
template<>
struct DataType< ::ingredientfinder::ingredientPosResponse>
{
  static const char* value()
  {
    return DataType< ::ingredientfinder::ingredientPos >::value();
  }
  static const char* value(const ::ingredientfinder::ingredientPosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INGREDIENTFINDER_MESSAGE_INGREDIENTPOS_H
