// Generated by gencpp from file userInterface/sayTTS.msg
// DO NOT EDIT!


#ifndef USERINTERFACE_MESSAGE_SAYTTS_H
#define USERINTERFACE_MESSAGE_SAYTTS_H

#include <ros/service_traits.h>


#include <userInterface/sayTTSRequest.h>
#include <userInterface/sayTTSResponse.h>


namespace userInterface
{

struct sayTTS
{

typedef sayTTSRequest Request;
typedef sayTTSResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct sayTTS
} // namespace userInterface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::userInterface::sayTTS > {
  static const char* value()
  {
    return "6f897d3845272d18053a750c1cfb862a";
  }

  static const char* value(const ::userInterface::sayTTS&) { return value(); }
};

template<>
struct DataType< ::userInterface::sayTTS > {
  static const char* value()
  {
    return "userInterface/sayTTS";
  }

  static const char* value(const ::userInterface::sayTTS&) { return value(); }
};


// service_traits::MD5Sum< ::userInterface::sayTTSRequest> should match 
// service_traits::MD5Sum< ::userInterface::sayTTS > 
template<>
struct MD5Sum< ::userInterface::sayTTSRequest>
{
  static const char* value()
  {
    return MD5Sum< ::userInterface::sayTTS >::value();
  }
  static const char* value(const ::userInterface::sayTTSRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::userInterface::sayTTSRequest> should match 
// service_traits::DataType< ::userInterface::sayTTS > 
template<>
struct DataType< ::userInterface::sayTTSRequest>
{
  static const char* value()
  {
    return DataType< ::userInterface::sayTTS >::value();
  }
  static const char* value(const ::userInterface::sayTTSRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::userInterface::sayTTSResponse> should match 
// service_traits::MD5Sum< ::userInterface::sayTTS > 
template<>
struct MD5Sum< ::userInterface::sayTTSResponse>
{
  static const char* value()
  {
    return MD5Sum< ::userInterface::sayTTS >::value();
  }
  static const char* value(const ::userInterface::sayTTSResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::userInterface::sayTTSResponse> should match 
// service_traits::DataType< ::userInterface::sayTTS > 
template<>
struct DataType< ::userInterface::sayTTSResponse>
{
  static const char* value()
  {
    return DataType< ::userInterface::sayTTS >::value();
  }
  static const char* value(const ::userInterface::sayTTSResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // USERINTERFACE_MESSAGE_SAYTTS_H
