// Generated by gencpp from file wristcontrol/scoopPositionRequest.msg
// DO NOT EDIT!


#ifndef WRISTCONTROL_MESSAGE_SCOOPPOSITIONREQUEST_H
#define WRISTCONTROL_MESSAGE_SCOOPPOSITIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wristcontrol
{
template <class ContainerAllocator>
struct scoopPositionRequest_
{
  typedef scoopPositionRequest_<ContainerAllocator> Type;

  scoopPositionRequest_()
    : position()  {
    }
  scoopPositionRequest_(const ContainerAllocator& _alloc)
    : position(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _position_type;
  _position_type position;




  typedef boost::shared_ptr< ::wristcontrol::scoopPositionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wristcontrol::scoopPositionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct scoopPositionRequest_

typedef ::wristcontrol::scoopPositionRequest_<std::allocator<void> > scoopPositionRequest;

typedef boost::shared_ptr< ::wristcontrol::scoopPositionRequest > scoopPositionRequestPtr;
typedef boost::shared_ptr< ::wristcontrol::scoopPositionRequest const> scoopPositionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wristcontrol::scoopPositionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wristcontrol::scoopPositionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wristcontrol

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wristcontrol::scoopPositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wristcontrol::scoopPositionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wristcontrol::scoopPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wristcontrol::scoopPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wristcontrol::scoopPositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wristcontrol::scoopPositionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wristcontrol::scoopPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d6afdd327a64a50f94a7d3a2de5435e3";
  }

  static const char* value(const ::wristcontrol::scoopPositionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd6afdd327a64a50fULL;
  static const uint64_t static_value2 = 0x94a7d3a2de5435e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::wristcontrol::scoopPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wristcontrol/scoopPositionRequest";
  }

  static const char* value(const ::wristcontrol::scoopPositionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wristcontrol::scoopPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string position\n\
";
  }

  static const char* value(const ::wristcontrol::scoopPositionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wristcontrol::scoopPositionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct scoopPositionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wristcontrol::scoopPositionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wristcontrol::scoopPositionRequest_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WRISTCONTROL_MESSAGE_SCOOPPOSITIONREQUEST_H
