// Generated by gencpp from file wristcontrol/scoopPosition.msg
// DO NOT EDIT!


#ifndef WRISTCONTROL_MESSAGE_SCOOPPOSITION_H
#define WRISTCONTROL_MESSAGE_SCOOPPOSITION_H

#include <ros/service_traits.h>


#include <wristcontrol/scoopPositionRequest.h>
#include <wristcontrol/scoopPositionResponse.h>


namespace wristcontrol
{

struct scoopPosition
{

typedef scoopPositionRequest Request;
typedef scoopPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct scoopPosition
} // namespace wristcontrol


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wristcontrol::scoopPosition > {
  static const char* value()
  {
    return "fbff76c87a69c0d7b6234363aee3ad07";
  }

  static const char* value(const ::wristcontrol::scoopPosition&) { return value(); }
};

template<>
struct DataType< ::wristcontrol::scoopPosition > {
  static const char* value()
  {
    return "wristcontrol/scoopPosition";
  }

  static const char* value(const ::wristcontrol::scoopPosition&) { return value(); }
};


// service_traits::MD5Sum< ::wristcontrol::scoopPositionRequest> should match 
// service_traits::MD5Sum< ::wristcontrol::scoopPosition > 
template<>
struct MD5Sum< ::wristcontrol::scoopPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wristcontrol::scoopPosition >::value();
  }
  static const char* value(const ::wristcontrol::scoopPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wristcontrol::scoopPositionRequest> should match 
// service_traits::DataType< ::wristcontrol::scoopPosition > 
template<>
struct DataType< ::wristcontrol::scoopPositionRequest>
{
  static const char* value()
  {
    return DataType< ::wristcontrol::scoopPosition >::value();
  }
  static const char* value(const ::wristcontrol::scoopPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wristcontrol::scoopPositionResponse> should match 
// service_traits::MD5Sum< ::wristcontrol::scoopPosition > 
template<>
struct MD5Sum< ::wristcontrol::scoopPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wristcontrol::scoopPosition >::value();
  }
  static const char* value(const ::wristcontrol::scoopPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wristcontrol::scoopPositionResponse> should match 
// service_traits::DataType< ::wristcontrol::scoopPosition > 
template<>
struct DataType< ::wristcontrol::scoopPositionResponse>
{
  static const char* value()
  {
    return DataType< ::wristcontrol::scoopPosition >::value();
  }
  static const char* value(const ::wristcontrol::scoopPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WRISTCONTROL_MESSAGE_SCOOPPOSITION_H
