// Generated by gencpp from file platedetector/assertNoPlateRequest.msg
// DO NOT EDIT!


#ifndef PLATEDETECTOR_MESSAGE_ASSERTNOPLATEREQUEST_H
#define PLATEDETECTOR_MESSAGE_ASSERTNOPLATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace platedetector
{
template <class ContainerAllocator>
struct assertNoPlateRequest_
{
  typedef assertNoPlateRequest_<ContainerAllocator> Type;

  assertNoPlateRequest_()
    {
    }
  assertNoPlateRequest_(const ContainerAllocator& _alloc)
    {
    }






  typedef boost::shared_ptr< ::platedetector::assertNoPlateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::platedetector::assertNoPlateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct assertNoPlateRequest_

typedef ::platedetector::assertNoPlateRequest_<std::allocator<void> > assertNoPlateRequest;

typedef boost::shared_ptr< ::platedetector::assertNoPlateRequest > assertNoPlateRequestPtr;
typedef boost::shared_ptr< ::platedetector::assertNoPlateRequest const> assertNoPlateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::platedetector::assertNoPlateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::platedetector::assertNoPlateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace platedetector

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::platedetector::assertNoPlateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::platedetector::assertNoPlateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platedetector::assertNoPlateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platedetector::assertNoPlateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platedetector::assertNoPlateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platedetector::assertNoPlateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::platedetector::assertNoPlateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::platedetector::assertNoPlateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::platedetector::assertNoPlateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "platedetector/assertNoPlateRequest";
  }

  static const char* value(const ::platedetector::assertNoPlateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::platedetector::assertNoPlateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::platedetector::assertNoPlateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::platedetector::assertNoPlateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct assertNoPlateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::platedetector::assertNoPlateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::platedetector::assertNoPlateRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PLATEDETECTOR_MESSAGE_ASSERTNOPLATEREQUEST_H
