// Generated by gencpp from file platedetector/assertNoPlate.msg
// DO NOT EDIT!


#ifndef PLATEDETECTOR_MESSAGE_ASSERTNOPLATE_H
#define PLATEDETECTOR_MESSAGE_ASSERTNOPLATE_H

#include <ros/service_traits.h>


#include <platedetector/assertNoPlateRequest.h>
#include <platedetector/assertNoPlateResponse.h>


namespace platedetector
{

struct assertNoPlate
{

typedef assertNoPlateRequest Request;
typedef assertNoPlateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct assertNoPlate
} // namespace platedetector


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::platedetector::assertNoPlate > {
  static const char* value()
  {
    return "f680ede81341c83926ff269af0efb2e6";
  }

  static const char* value(const ::platedetector::assertNoPlate&) { return value(); }
};

template<>
struct DataType< ::platedetector::assertNoPlate > {
  static const char* value()
  {
    return "platedetector/assertNoPlate";
  }

  static const char* value(const ::platedetector::assertNoPlate&) { return value(); }
};


// service_traits::MD5Sum< ::platedetector::assertNoPlateRequest> should match 
// service_traits::MD5Sum< ::platedetector::assertNoPlate > 
template<>
struct MD5Sum< ::platedetector::assertNoPlateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::platedetector::assertNoPlate >::value();
  }
  static const char* value(const ::platedetector::assertNoPlateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::platedetector::assertNoPlateRequest> should match 
// service_traits::DataType< ::platedetector::assertNoPlate > 
template<>
struct DataType< ::platedetector::assertNoPlateRequest>
{
  static const char* value()
  {
    return DataType< ::platedetector::assertNoPlate >::value();
  }
  static const char* value(const ::platedetector::assertNoPlateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::platedetector::assertNoPlateResponse> should match 
// service_traits::MD5Sum< ::platedetector::assertNoPlate > 
template<>
struct MD5Sum< ::platedetector::assertNoPlateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::platedetector::assertNoPlate >::value();
  }
  static const char* value(const ::platedetector::assertNoPlateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::platedetector::assertNoPlateResponse> should match 
// service_traits::DataType< ::platedetector::assertNoPlate > 
template<>
struct DataType< ::platedetector::assertNoPlateResponse>
{
  static const char* value()
  {
    return DataType< ::platedetector::assertNoPlate >::value();
  }
  static const char* value(const ::platedetector::assertNoPlateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLATEDETECTOR_MESSAGE_ASSERTNOPLATE_H
