// Generated by gencpp from file platformcontrol/findLeftBoundary.msg
// DO NOT EDIT!


#ifndef PLATFORMCONTROL_MESSAGE_FINDLEFTBOUNDARY_H
#define PLATFORMCONTROL_MESSAGE_FINDLEFTBOUNDARY_H

#include <ros/service_traits.h>


#include <platformcontrol/findLeftBoundaryRequest.h>
#include <platformcontrol/findLeftBoundaryResponse.h>


namespace platformcontrol
{

struct findLeftBoundary
{

typedef findLeftBoundaryRequest Request;
typedef findLeftBoundaryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct findLeftBoundary
} // namespace platformcontrol


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::platformcontrol::findLeftBoundary > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::platformcontrol::findLeftBoundary&) { return value(); }
};

template<>
struct DataType< ::platformcontrol::findLeftBoundary > {
  static const char* value()
  {
    return "platformcontrol/findLeftBoundary";
  }

  static const char* value(const ::platformcontrol::findLeftBoundary&) { return value(); }
};


// service_traits::MD5Sum< ::platformcontrol::findLeftBoundaryRequest> should match 
// service_traits::MD5Sum< ::platformcontrol::findLeftBoundary > 
template<>
struct MD5Sum< ::platformcontrol::findLeftBoundaryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::platformcontrol::findLeftBoundary >::value();
  }
  static const char* value(const ::platformcontrol::findLeftBoundaryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::platformcontrol::findLeftBoundaryRequest> should match 
// service_traits::DataType< ::platformcontrol::findLeftBoundary > 
template<>
struct DataType< ::platformcontrol::findLeftBoundaryRequest>
{
  static const char* value()
  {
    return DataType< ::platformcontrol::findLeftBoundary >::value();
  }
  static const char* value(const ::platformcontrol::findLeftBoundaryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::platformcontrol::findLeftBoundaryResponse> should match 
// service_traits::MD5Sum< ::platformcontrol::findLeftBoundary > 
template<>
struct MD5Sum< ::platformcontrol::findLeftBoundaryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::platformcontrol::findLeftBoundary >::value();
  }
  static const char* value(const ::platformcontrol::findLeftBoundaryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::platformcontrol::findLeftBoundaryResponse> should match 
// service_traits::DataType< ::platformcontrol::findLeftBoundary > 
template<>
struct DataType< ::platformcontrol::findLeftBoundaryResponse>
{
  static const char* value()
  {
    return DataType< ::platformcontrol::findLeftBoundary >::value();
  }
  static const char* value(const ::platformcontrol::findLeftBoundaryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLATFORMCONTROL_MESSAGE_FINDLEFTBOUNDARY_H
