// Generated by gencpp from file platformcontrol/findLeftBoundaryRequest.msg
// DO NOT EDIT!


#ifndef PLATFORMCONTROL_MESSAGE_FINDLEFTBOUNDARYREQUEST_H
#define PLATFORMCONTROL_MESSAGE_FINDLEFTBOUNDARYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace platformcontrol
{
template <class ContainerAllocator>
struct findLeftBoundaryRequest_
{
  typedef findLeftBoundaryRequest_<ContainerAllocator> Type;

  findLeftBoundaryRequest_()
    {
    }
  findLeftBoundaryRequest_(const ContainerAllocator& _alloc)
    {
    }






  typedef boost::shared_ptr< ::platformcontrol::findLeftBoundaryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::platformcontrol::findLeftBoundaryRequest_<ContainerAllocator> const> ConstPtr;

}; // struct findLeftBoundaryRequest_

typedef ::platformcontrol::findLeftBoundaryRequest_<std::allocator<void> > findLeftBoundaryRequest;

typedef boost::shared_ptr< ::platformcontrol::findLeftBoundaryRequest > findLeftBoundaryRequestPtr;
typedef boost::shared_ptr< ::platformcontrol::findLeftBoundaryRequest const> findLeftBoundaryRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::platformcontrol::findLeftBoundaryRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::platformcontrol::findLeftBoundaryRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace platformcontrol

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::platformcontrol::findLeftBoundaryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::platformcontrol::findLeftBoundaryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platformcontrol::findLeftBoundaryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platformcontrol::findLeftBoundaryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platformcontrol::findLeftBoundaryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platformcontrol::findLeftBoundaryRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::platformcontrol::findLeftBoundaryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::platformcontrol::findLeftBoundaryRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::platformcontrol::findLeftBoundaryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "platformcontrol/findLeftBoundaryRequest";
  }

  static const char* value(const ::platformcontrol::findLeftBoundaryRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::platformcontrol::findLeftBoundaryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::platformcontrol::findLeftBoundaryRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::platformcontrol::findLeftBoundaryRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct findLeftBoundaryRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::platformcontrol::findLeftBoundaryRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::platformcontrol::findLeftBoundaryRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PLATFORMCONTROL_MESSAGE_FINDLEFTBOUNDARYREQUEST_H
