// Generated by gencpp from file jobqueue/addJobToQueueRequest.msg
// DO NOT EDIT!


#ifndef JOBQUEUE_MESSAGE_ADDJOBTOQUEUEREQUEST_H
#define JOBQUEUE_MESSAGE_ADDJOBTOQUEUEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jobqueue
{
template <class ContainerAllocator>
struct addJobToQueueRequest_
{
  typedef addJobToQueueRequest_<ContainerAllocator> Type;

  addJobToQueueRequest_()
    : job()  {
    }
  addJobToQueueRequest_(const ContainerAllocator& _alloc)
    : job(_alloc)  {
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _job_type;
  _job_type job;




  typedef boost::shared_ptr< ::jobqueue::addJobToQueueRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jobqueue::addJobToQueueRequest_<ContainerAllocator> const> ConstPtr;

}; // struct addJobToQueueRequest_

typedef ::jobqueue::addJobToQueueRequest_<std::allocator<void> > addJobToQueueRequest;

typedef boost::shared_ptr< ::jobqueue::addJobToQueueRequest > addJobToQueueRequestPtr;
typedef boost::shared_ptr< ::jobqueue::addJobToQueueRequest const> addJobToQueueRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jobqueue::addJobToQueueRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jobqueue::addJobToQueueRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace jobqueue

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'fedar_msgs': ['/home/gijs/Fedar/src/fedar_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::jobqueue::addJobToQueueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jobqueue::addJobToQueueRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jobqueue::addJobToQueueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jobqueue::addJobToQueueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jobqueue::addJobToQueueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jobqueue::addJobToQueueRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jobqueue::addJobToQueueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "32e32d3795164313cf89baa7aa45d2c9";
  }

  static const char* value(const ::jobqueue::addJobToQueueRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x32e32d3795164313ULL;
  static const uint64_t static_value2 = 0xcf89baa7aa45d2c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::jobqueue::addJobToQueueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jobqueue/addJobToQueueRequest";
  }

  static const char* value(const ::jobqueue::addJobToQueueRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jobqueue::addJobToQueueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] job\n\
";
  }

  static const char* value(const ::jobqueue::addJobToQueueRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jobqueue::addJobToQueueRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.job);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct addJobToQueueRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jobqueue::addJobToQueueRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jobqueue::addJobToQueueRequest_<ContainerAllocator>& v)
  {
    s << indent << "job[]" << std::endl;
    for (size_t i = 0; i < v.job.size(); ++i)
    {
      s << indent << "  job[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.job[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // JOBQUEUE_MESSAGE_ADDJOBTOQUEUEREQUEST_H
