// Generated by gencpp from file jobqueue/addJobToQueue.msg
// DO NOT EDIT!


#ifndef JOBQUEUE_MESSAGE_ADDJOBTOQUEUE_H
#define JOBQUEUE_MESSAGE_ADDJOBTOQUEUE_H

#include <ros/service_traits.h>


#include <jobqueue/addJobToQueueRequest.h>
#include <jobqueue/addJobToQueueResponse.h>


namespace jobqueue
{

struct addJobToQueue
{

typedef addJobToQueueRequest Request;
typedef addJobToQueueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct addJobToQueue
} // namespace jobqueue


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jobqueue::addJobToQueue > {
  static const char* value()
  {
    return "c35b579608502459517da7a57bc48b25";
  }

  static const char* value(const ::jobqueue::addJobToQueue&) { return value(); }
};

template<>
struct DataType< ::jobqueue::addJobToQueue > {
  static const char* value()
  {
    return "jobqueue/addJobToQueue";
  }

  static const char* value(const ::jobqueue::addJobToQueue&) { return value(); }
};


// service_traits::MD5Sum< ::jobqueue::addJobToQueueRequest> should match 
// service_traits::MD5Sum< ::jobqueue::addJobToQueue > 
template<>
struct MD5Sum< ::jobqueue::addJobToQueueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jobqueue::addJobToQueue >::value();
  }
  static const char* value(const ::jobqueue::addJobToQueueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jobqueue::addJobToQueueRequest> should match 
// service_traits::DataType< ::jobqueue::addJobToQueue > 
template<>
struct DataType< ::jobqueue::addJobToQueueRequest>
{
  static const char* value()
  {
    return DataType< ::jobqueue::addJobToQueue >::value();
  }
  static const char* value(const ::jobqueue::addJobToQueueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jobqueue::addJobToQueueResponse> should match 
// service_traits::MD5Sum< ::jobqueue::addJobToQueue > 
template<>
struct MD5Sum< ::jobqueue::addJobToQueueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jobqueue::addJobToQueue >::value();
  }
  static const char* value(const ::jobqueue::addJobToQueueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jobqueue::addJobToQueueResponse> should match 
// service_traits::DataType< ::jobqueue::addJobToQueue > 
template<>
struct DataType< ::jobqueue::addJobToQueueResponse>
{
  static const char* value()
  {
    return DataType< ::jobqueue::addJobToQueue >::value();
  }
  static const char* value(const ::jobqueue::addJobToQueueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JOBQUEUE_MESSAGE_ADDJOBTOQUEUE_H
