// Generated by gencpp from file jobqueue/nextjob.msg
// DO NOT EDIT!


#ifndef JOBQUEUE_MESSAGE_NEXTJOB_H
#define JOBQUEUE_MESSAGE_NEXTJOB_H

#include <ros/service_traits.h>


#include <jobqueue/nextjobRequest.h>
#include <jobqueue/nextjobResponse.h>


namespace jobqueue
{

struct nextjob
{

typedef nextjobRequest Request;
typedef nextjobResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct nextjob
} // namespace jobqueue


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jobqueue::nextjob > {
  static const char* value()
  {
    return "32e32d3795164313cf89baa7aa45d2c9";
  }

  static const char* value(const ::jobqueue::nextjob&) { return value(); }
};

template<>
struct DataType< ::jobqueue::nextjob > {
  static const char* value()
  {
    return "jobqueue/nextjob";
  }

  static const char* value(const ::jobqueue::nextjob&) { return value(); }
};


// service_traits::MD5Sum< ::jobqueue::nextjobRequest> should match 
// service_traits::MD5Sum< ::jobqueue::nextjob > 
template<>
struct MD5Sum< ::jobqueue::nextjobRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jobqueue::nextjob >::value();
  }
  static const char* value(const ::jobqueue::nextjobRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jobqueue::nextjobRequest> should match 
// service_traits::DataType< ::jobqueue::nextjob > 
template<>
struct DataType< ::jobqueue::nextjobRequest>
{
  static const char* value()
  {
    return DataType< ::jobqueue::nextjob >::value();
  }
  static const char* value(const ::jobqueue::nextjobRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jobqueue::nextjobResponse> should match 
// service_traits::MD5Sum< ::jobqueue::nextjob > 
template<>
struct MD5Sum< ::jobqueue::nextjobResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jobqueue::nextjob >::value();
  }
  static const char* value(const ::jobqueue::nextjobResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jobqueue::nextjobResponse> should match 
// service_traits::DataType< ::jobqueue::nextjob > 
template<>
struct DataType< ::jobqueue::nextjobResponse>
{
  static const char* value()
  {
    return DataType< ::jobqueue::nextjob >::value();
  }
  static const char* value(const ::jobqueue::nextjobResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JOBQUEUE_MESSAGE_NEXTJOB_H
