// Generated by gencpp from file jobqueue/nextjobRequest.msg
// DO NOT EDIT!


#ifndef JOBQUEUE_MESSAGE_NEXTJOBREQUEST_H
#define JOBQUEUE_MESSAGE_NEXTJOBREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jobqueue
{
template <class ContainerAllocator>
struct nextjobRequest_
{
  typedef nextjobRequest_<ContainerAllocator> Type;

  nextjobRequest_()
    {
    }
  nextjobRequest_(const ContainerAllocator& _alloc)
    {
    }






  typedef boost::shared_ptr< ::jobqueue::nextjobRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jobqueue::nextjobRequest_<ContainerAllocator> const> ConstPtr;

}; // struct nextjobRequest_

typedef ::jobqueue::nextjobRequest_<std::allocator<void> > nextjobRequest;

typedef boost::shared_ptr< ::jobqueue::nextjobRequest > nextjobRequestPtr;
typedef boost::shared_ptr< ::jobqueue::nextjobRequest const> nextjobRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jobqueue::nextjobRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jobqueue::nextjobRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace jobqueue

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'jobqueue': ['/home/gijs/Fedar/src/jobqueue/msg', '/home/gijs/Fedar/src/jobqueue/msg'], 'fedar_msgs': ['/home/gijs/Fedar/src/fedar_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::jobqueue::nextjobRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jobqueue::nextjobRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jobqueue::nextjobRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jobqueue::nextjobRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jobqueue::nextjobRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jobqueue::nextjobRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jobqueue::nextjobRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::jobqueue::nextjobRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::jobqueue::nextjobRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jobqueue/nextjobRequest";
  }

  static const char* value(const ::jobqueue::nextjobRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jobqueue::nextjobRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::jobqueue::nextjobRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jobqueue::nextjobRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct nextjobRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jobqueue::nextjobRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::jobqueue::nextjobRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // JOBQUEUE_MESSAGE_NEXTJOBREQUEST_H
