// Generated by gencpp from file jobqueue/task.msg
// DO NOT EDIT!


#ifndef JOBQUEUE_MESSAGE_TASK_H
#define JOBQUEUE_MESSAGE_TASK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jobqueue
{
template <class ContainerAllocator>
struct task_
{
  typedef task_<ContainerAllocator> Type;

  task_()
    : ingredients()  {
    }
  task_(const ContainerAllocator& _alloc)
    : ingredients(_alloc)  {
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _ingredients_type;
  _ingredients_type ingredients;




  typedef boost::shared_ptr< ::jobqueue::task_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jobqueue::task_<ContainerAllocator> const> ConstPtr;

}; // struct task_

typedef ::jobqueue::task_<std::allocator<void> > task;

typedef boost::shared_ptr< ::jobqueue::task > taskPtr;
typedef boost::shared_ptr< ::jobqueue::task const> taskConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jobqueue::task_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jobqueue::task_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace jobqueue

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'jobqueue': ['/home/gijs/Fedar/src/jobqueue/msg', '/home/gijs/Fedar/src/jobqueue/msg'], 'fedar_msgs': ['/home/gijs/Fedar/src/fedar_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::jobqueue::task_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jobqueue::task_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jobqueue::task_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jobqueue::task_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jobqueue::task_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jobqueue::task_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jobqueue::task_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dfec60150d2a09a3ef1a56a635795144";
  }

  static const char* value(const ::jobqueue::task_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdfec60150d2a09a3ULL;
  static const uint64_t static_value2 = 0xef1a56a635795144ULL;
};

template<class ContainerAllocator>
struct DataType< ::jobqueue::task_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jobqueue/task";
  }

  static const char* value(const ::jobqueue::task_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jobqueue::task_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] ingredients\n\
";
  }

  static const char* value(const ::jobqueue::task_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jobqueue::task_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ingredients);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct task_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jobqueue::task_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jobqueue::task_<ContainerAllocator>& v)
  {
    s << indent << "ingredients[]" << std::endl;
    for (size_t i = 0; i < v.ingredients.size(); ++i)
    {
      s << indent << "  ingredients[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.ingredients[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // JOBQUEUE_MESSAGE_TASK_H
