// Generated by gencpp from file armcontrol/armInitializeMotors.msg
// DO NOT EDIT!


#ifndef ARMCONTROL_MESSAGE_ARMINITIALIZEMOTORS_H
#define ARMCONTROL_MESSAGE_ARMINITIALIZEMOTORS_H

#include <ros/service_traits.h>


#include <armcontrol/armInitializeMotorsRequest.h>
#include <armcontrol/armInitializeMotorsResponse.h>


namespace armcontrol
{

struct armInitializeMotors
{

typedef armInitializeMotorsRequest Request;
typedef armInitializeMotorsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct armInitializeMotors
} // namespace armcontrol


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::armcontrol::armInitializeMotors > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::armcontrol::armInitializeMotors&) { return value(); }
};

template<>
struct DataType< ::armcontrol::armInitializeMotors > {
  static const char* value()
  {
    return "armcontrol/armInitializeMotors";
  }

  static const char* value(const ::armcontrol::armInitializeMotors&) { return value(); }
};


// service_traits::MD5Sum< ::armcontrol::armInitializeMotorsRequest> should match 
// service_traits::MD5Sum< ::armcontrol::armInitializeMotors > 
template<>
struct MD5Sum< ::armcontrol::armInitializeMotorsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::armcontrol::armInitializeMotors >::value();
  }
  static const char* value(const ::armcontrol::armInitializeMotorsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::armcontrol::armInitializeMotorsRequest> should match 
// service_traits::DataType< ::armcontrol::armInitializeMotors > 
template<>
struct DataType< ::armcontrol::armInitializeMotorsRequest>
{
  static const char* value()
  {
    return DataType< ::armcontrol::armInitializeMotors >::value();
  }
  static const char* value(const ::armcontrol::armInitializeMotorsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::armcontrol::armInitializeMotorsResponse> should match 
// service_traits::MD5Sum< ::armcontrol::armInitializeMotors > 
template<>
struct MD5Sum< ::armcontrol::armInitializeMotorsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::armcontrol::armInitializeMotors >::value();
  }
  static const char* value(const ::armcontrol::armInitializeMotorsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::armcontrol::armInitializeMotorsResponse> should match 
// service_traits::DataType< ::armcontrol::armInitializeMotors > 
template<>
struct DataType< ::armcontrol::armInitializeMotorsResponse>
{
  static const char* value()
  {
    return DataType< ::armcontrol::armInitializeMotors >::value();
  }
  static const char* value(const ::armcontrol::armInitializeMotorsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARMCONTROL_MESSAGE_ARMINITIALIZEMOTORS_H
