// Generated by gencpp from file armcontrol/armPosition.msg
// DO NOT EDIT!


#ifndef ARMCONTROL_MESSAGE_ARMPOSITION_H
#define ARMCONTROL_MESSAGE_ARMPOSITION_H

#include <ros/service_traits.h>


#include <armcontrol/armPositionRequest.h>
#include <armcontrol/armPositionResponse.h>


namespace armcontrol
{

struct armPosition
{

typedef armPositionRequest Request;
typedef armPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct armPosition
} // namespace armcontrol


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::armcontrol::armPosition > {
  static const char* value()
  {
    return "6b2e53660d6841d8f112321c6040b63e";
  }

  static const char* value(const ::armcontrol::armPosition&) { return value(); }
};

template<>
struct DataType< ::armcontrol::armPosition > {
  static const char* value()
  {
    return "armcontrol/armPosition";
  }

  static const char* value(const ::armcontrol::armPosition&) { return value(); }
};


// service_traits::MD5Sum< ::armcontrol::armPositionRequest> should match 
// service_traits::MD5Sum< ::armcontrol::armPosition > 
template<>
struct MD5Sum< ::armcontrol::armPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::armcontrol::armPosition >::value();
  }
  static const char* value(const ::armcontrol::armPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::armcontrol::armPositionRequest> should match 
// service_traits::DataType< ::armcontrol::armPosition > 
template<>
struct DataType< ::armcontrol::armPositionRequest>
{
  static const char* value()
  {
    return DataType< ::armcontrol::armPosition >::value();
  }
  static const char* value(const ::armcontrol::armPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::armcontrol::armPositionResponse> should match 
// service_traits::MD5Sum< ::armcontrol::armPosition > 
template<>
struct MD5Sum< ::armcontrol::armPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::armcontrol::armPosition >::value();
  }
  static const char* value(const ::armcontrol::armPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::armcontrol::armPositionResponse> should match 
// service_traits::DataType< ::armcontrol::armPosition > 
template<>
struct DataType< ::armcontrol::armPositionResponse>
{
  static const char* value()
  {
    return DataType< ::armcontrol::armPosition >::value();
  }
  static const char* value(const ::armcontrol::armPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARMCONTROL_MESSAGE_ARMPOSITION_H
